"""Static slash command catalog entries."""

from __future__ import annotations

from typing import Any


REQUIRED_BACKEND_CAPABILITIES = {
    "/help": "cli.help",
    "/undo": "session.undo",
    "/compact": "session.context_compaction",
    "/model": "session.model_selection",
    "/effort": "session.reasoning_effort",
    "/yolo": "session.approval_mode",
    "/status": "project.snapshot_read",
    "/quit": "cli.exit",
    "/new": "project.workspace_create",
    "/open": "project.workspace_open",
    "/handoff": "project.handoff_summary",
    "/export": "project.export",
    "/doctor": "project.diagnostics",
    "/flows": "flow.template_catalog_read",
    "/flow preview": "flow.template_preview_read",
    "/flow start": "flow.run_start",
    "/flow pause": "flow.run_pause",
    "/flow resume": "flow.run_resume",
    "/flow fork": "flow.run_fork",
    "/phase": "workflow.phase_state",
    "/plan": "workflow.plan_state",
    "/experiments": "experiment.board_state",
    "/runs": "experiment.run_index",
    "/run show": "experiment.run_detail",
    "/run compare": "experiment.run_compare",
    "/run fork": "experiment.run_fork",
    "/metrics": "experiment.metrics_read",
    "/artifacts": "artifact.index_read",
    "/tools": "tool.catalog_read",
    "/jobs": "job.status_read",
    "/approve": "approval.decision_record",
    "/deny": "approval.decision_record",
    "/permissions": "policy.permissions_manage",
    "/budget": "budget.controls",
    "/evidence": "evidence.search",
    "/decisions": "decision.log_read",
    "/assumptions": "assumption.registry_read",
    "/memory": "memory.project_read",
    "/ledger": "ledger.read",
    "/ledger verify": "ledger.verify",
    "/proof bundle": "proof.bundle_create",
    "/diff": "workspace.diff_read",
    "/test": "test.runner",
    "/rollback": "workspace.rollback",
    "/commit": "vcs.commit_prepare",
    "/pr": "vcs.pr_prepare",
    "/data snapshot": "data.snapshot_create",
    "/data diff": "data.snapshot_compare",
    "/eval": "evaluation.run",
    "/package": "package.build",
}


def build_command_registry(command_spec: type[Any]) -> tuple[Any, ...]:
    """Build command specs without keeping the large catalog in parser code."""

    CommandSpec = command_spec
    def spec(**kwargs: Any) -> Any:
        return CommandSpec(
            required_backend_capability=REQUIRED_BACKEND_CAPABILITIES[kwargs["name"]],
            **kwargs,
        )

    return (
        spec(
            name="/help",
            description="Show this help",
            risk_level="safe",
            mutates_state=False,
        ),
        spec(
            name="/undo",
            description="Undo last turn",
            risk_level="medium",
            mutates_state=True,
        ),
        spec(
            name="/compact",
            description="Compact context window",
            risk_level="medium",
            mutates_state=True,
            group="evidence",
        ),
        spec(
            name="/model",
            description="Show available models or switch",
            arguments="[id]",
            risk_level="low",
            mutates_state=True,
        ),
        spec(
            name="/effort",
            description="Reasoning effort (minimal|low|medium|high|xhigh|max|off)",
            arguments="[level]",
            risk_level="low",
            mutates_state=True,
        ),
        spec(
            name="/yolo",
            description="Toggle auto-approve mode",
            risk_level="high",
            mutates_state=True,
        ),
        spec(
            name="/status",
            description="Current model, effort, and turn count",
            risk_level="safe",
            mutates_state=False,
            group="project",
        ),
        spec(
            name="/quit",
            description="Exit",
            risk_level="safe",
            mutates_state=False,
            aliases=("/exit", "quit", "exit"),
        ),
        spec(
            name="/new",
            description="Create a project workspace",
            arguments="<name|path>",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="project",
        ),
        spec(
            name="/open",
            description="Open an existing project workspace",
            arguments="<path>",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="project",
        ),
        spec(
            name="/handoff",
            description="Prepare a project handoff summary",
            arguments="[path]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="project",
        ),
        spec(
            name="/export",
            description="Export project state or reports",
            arguments="[target]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="project",
        ),
        spec(
            name="/doctor",
            description="Run environment diagnostics",
            risk_level="low",
            mutates_state=False,
            implemented=False,
            group="project",
        ),
        spec(
            name="/flows",
            description="List saved flows and flow commands",
            risk_level="safe",
            mutates_state=False,
            group="flow",
        ),
        spec(
            name="/flow preview",
            description="Preview a flow before running it",
            arguments="<id>",
            risk_level="low",
            mutates_state=False,
            group="flow",
        ),
        spec(
            name="/flow start",
            description="Start a flow",
            arguments="<flow>",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        spec(
            name="/flow pause",
            description="Pause the active flow",
            arguments="[id]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        spec(
            name="/flow resume",
            description="Resume a paused flow",
            arguments="[id]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        spec(
            name="/flow fork",
            description="Fork a flow from an existing run",
            arguments="<id> [name]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        spec(
            name="/phase",
            description="Show or switch the current project phase",
            arguments="[name]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        spec(
            name="/plan",
            description="Create or inspect an execution plan",
            arguments="[goal]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        spec(
            name="/experiments",
            description="Manage experiment flags",
            arguments="[name] [on|off]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="experiment",
        ),
        spec(
            name="/runs",
            description="List experiment runs",
            arguments="[filter]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        spec(
            name="/run show",
            description="Show run details",
            arguments="[id]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        spec(
            name="/run compare",
            description="Compare two runs",
            arguments="<left> <right>",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        spec(
            name="/run fork",
            description="Fork a run configuration",
            arguments="<id>",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="experiment",
        ),
        spec(
            name="/metrics",
            description="Show run metrics",
            arguments="[run]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        spec(
            name="/artifacts",
            description="List or inspect run artifacts",
            arguments="[id]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        spec(
            name="/tools",
            description="List available tools",
            arguments="[filter]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="tools",
        ),
        spec(
            name="/jobs",
            description="List background jobs",
            arguments="[filter]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="tools",
        ),
        spec(
            name="/approve",
            description="Approve a pending action",
            arguments="<id>",
            risk_level="high",
            mutates_state=True,
            implemented=False,
            group="tools",
        ),
        spec(
            name="/deny",
            description="Deny a pending action",
            arguments="<id>",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="tools",
        ),
        spec(
            name="/permissions",
            description="Show or adjust tool permissions",
            arguments="[scope]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="tools",
        ),
        spec(
            name="/budget",
            description="Show or set budget controls",
            arguments="[limit]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="tools",
        ),
        spec(
            name="/evidence",
            description="Search evidence records",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        spec(
            name="/decisions",
            description="List recorded decisions",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        spec(
            name="/assumptions",
            description="List tracked assumptions",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        spec(
            name="/memory",
            description="Inspect saved memory",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        spec(
            name="/ledger",
            description="Inspect the project ledger",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        spec(
            name="/ledger verify",
            description="Verify ledger integrity",
            arguments="[bundle]",
            risk_level="low",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        spec(
            name="/proof bundle",
            description="Create a proof bundle",
            arguments="[run]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="evidence",
        ),
        spec(
            name="/diff",
            description="Show code or workspace diffs",
            arguments="[target]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="code",
        ),
        spec(
            name="/test",
            description="Run tests",
            arguments="[selector]",
            risk_level="medium",
            mutates_state=False,
            implemented=False,
            group="code",
        ),
        spec(
            name="/rollback",
            description="Roll back a change or run",
            arguments="<target>",
            risk_level="high",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        spec(
            name="/commit",
            description="Prepare a commit",
            arguments="[message]",
            risk_level="high",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        spec(
            name="/pr",
            description="Prepare a pull request",
            arguments="[title]",
            risk_level="high",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        spec(
            name="/data snapshot",
            description="Create a data snapshot",
            arguments="[name]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        spec(
            name="/data diff",
            description="Compare data snapshots",
            arguments="<left> <right>",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="code",
        ),
        spec(
            name="/eval",
            description="Run an evaluation suite",
            arguments="[suite]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        spec(
            name="/package",
            description="Build a package artifact",
            arguments="[target]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
    )
