"""Static slash command catalog entries."""

from __future__ import annotations

from typing import Any


def build_command_registry(command_spec: type[Any]) -> tuple[Any, ...]:
    """Build command specs without keeping the large catalog in parser code."""

    CommandSpec = command_spec
    return (
        CommandSpec(
            name="/help",
            description="Show this help",
            risk_level="safe",
            mutates_state=False,
        ),
        CommandSpec(
            name="/undo",
            description="Undo last turn",
            risk_level="medium",
            mutates_state=True,
        ),
        CommandSpec(
            name="/compact",
            description="Compact context window",
            risk_level="medium",
            mutates_state=True,
            group="evidence",
        ),
        CommandSpec(
            name="/model",
            description="Show available models or switch",
            arguments="[id]",
            risk_level="low",
            mutates_state=True,
        ),
        CommandSpec(
            name="/effort",
            description="Reasoning effort (minimal|low|medium|high|xhigh|max|off)",
            arguments="[level]",
            risk_level="low",
            mutates_state=True,
        ),
        CommandSpec(
            name="/yolo",
            description="Toggle auto-approve mode",
            risk_level="high",
            mutates_state=True,
        ),
        CommandSpec(
            name="/status",
            description="Current model, effort, and turn count",
            risk_level="safe",
            mutates_state=False,
            group="project",
        ),
        CommandSpec(
            name="/quit",
            description="Exit",
            risk_level="safe",
            mutates_state=False,
            aliases=("/exit", "quit", "exit"),
        ),
        CommandSpec(
            name="/new",
            description="Create a project workspace",
            arguments="<name|path>",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="project",
        ),
        CommandSpec(
            name="/open",
            description="Open an existing project workspace",
            arguments="<path>",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="project",
        ),
        CommandSpec(
            name="/handoff",
            description="Prepare a project handoff summary",
            arguments="[path]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="project",
        ),
        CommandSpec(
            name="/export",
            description="Export project state or reports",
            arguments="[target]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="project",
        ),
        CommandSpec(
            name="/doctor",
            description="Run environment diagnostics",
            risk_level="low",
            mutates_state=False,
            implemented=False,
            group="project",
        ),
        CommandSpec(
            name="/flows",
            description="List saved flows and flow commands",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="flow",
        ),
        CommandSpec(
            name="/flow preview",
            description="Preview a flow before running it",
            arguments="<flow>",
            risk_level="low",
            mutates_state=False,
            implemented=False,
            group="flow",
        ),
        CommandSpec(
            name="/flow start",
            description="Start a flow",
            arguments="<flow>",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        CommandSpec(
            name="/flow pause",
            description="Pause the active flow",
            arguments="[id]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        CommandSpec(
            name="/flow resume",
            description="Resume a paused flow",
            arguments="[id]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        CommandSpec(
            name="/flow fork",
            description="Fork a flow from an existing run",
            arguments="<id> [name]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        CommandSpec(
            name="/phase",
            description="Show or switch the current project phase",
            arguments="[name]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        CommandSpec(
            name="/plan",
            description="Create or inspect an execution plan",
            arguments="[goal]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="flow",
        ),
        CommandSpec(
            name="/experiments",
            description="Manage experiment flags",
            arguments="[name] [on|off]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="experiment",
        ),
        CommandSpec(
            name="/runs",
            description="List experiment runs",
            arguments="[filter]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        CommandSpec(
            name="/run show",
            description="Show run details",
            arguments="[id]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        CommandSpec(
            name="/run compare",
            description="Compare two runs",
            arguments="<left> <right>",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        CommandSpec(
            name="/run fork",
            description="Fork a run configuration",
            arguments="<id>",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="experiment",
        ),
        CommandSpec(
            name="/metrics",
            description="Show run metrics",
            arguments="[run]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        CommandSpec(
            name="/artifacts",
            description="List or inspect run artifacts",
            arguments="[id]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="experiment",
        ),
        CommandSpec(
            name="/tools",
            description="List available tools",
            arguments="[filter]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="tools",
        ),
        CommandSpec(
            name="/jobs",
            description="List background jobs",
            arguments="[filter]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="tools",
        ),
        CommandSpec(
            name="/approve",
            description="Approve a pending action",
            arguments="<id>",
            risk_level="high",
            mutates_state=True,
            implemented=False,
            group="tools",
        ),
        CommandSpec(
            name="/deny",
            description="Deny a pending action",
            arguments="<id>",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="tools",
        ),
        CommandSpec(
            name="/permissions",
            description="Show or adjust tool permissions",
            arguments="[scope]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="tools",
        ),
        CommandSpec(
            name="/budget",
            description="Show or set budget controls",
            arguments="[limit]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="tools",
        ),
        CommandSpec(
            name="/evidence",
            description="Search evidence records",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        CommandSpec(
            name="/decisions",
            description="List recorded decisions",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        CommandSpec(
            name="/assumptions",
            description="List tracked assumptions",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        CommandSpec(
            name="/memory",
            description="Inspect saved memory",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        CommandSpec(
            name="/ledger",
            description="Inspect the project ledger",
            arguments="[query]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        CommandSpec(
            name="/ledger verify",
            description="Verify ledger integrity",
            arguments="[bundle]",
            risk_level="low",
            mutates_state=False,
            implemented=False,
            group="evidence",
        ),
        CommandSpec(
            name="/proof bundle",
            description="Create a proof bundle",
            arguments="[run]",
            risk_level="low",
            mutates_state=True,
            implemented=False,
            group="evidence",
        ),
        CommandSpec(
            name="/diff",
            description="Show code or workspace diffs",
            arguments="[target]",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="code",
        ),
        CommandSpec(
            name="/test",
            description="Run tests",
            arguments="[selector]",
            risk_level="medium",
            mutates_state=False,
            implemented=False,
            group="code",
        ),
        CommandSpec(
            name="/rollback",
            description="Roll back a change or run",
            arguments="<target>",
            risk_level="high",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        CommandSpec(
            name="/commit",
            description="Prepare a commit",
            arguments="[message]",
            risk_level="high",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        CommandSpec(
            name="/pr",
            description="Prepare a pull request",
            arguments="[title]",
            risk_level="high",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        CommandSpec(
            name="/data snapshot",
            description="Create a data snapshot",
            arguments="[name]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        CommandSpec(
            name="/data diff",
            description="Compare data snapshots",
            arguments="<left> <right>",
            risk_level="safe",
            mutates_state=False,
            implemented=False,
            group="code",
        ),
        CommandSpec(
            name="/eval",
            description="Run an evaluation suite",
            arguments="[suite]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
        CommandSpec(
            name="/package",
            description="Build a package artifact",
            arguments="[target]",
            risk_level="medium",
            mutates_state=True,
            implemented=False,
            group="code",
        ),
    )
